# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BucketNames(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'cloud': 'list[str]',
        'local': 'list[str]'
    }

    attribute_map = {
        'cloud': 'cloud',
        'local': 'local'
    }

    def __init__(self, cloud=None, local=None):  # noqa: E501
        """BucketNames - a model defined in OpenAPI"""  # noqa: E501

        self._cloud = None
        self._local = None
        self.discriminator = None

        if cloud is not None:
            self.cloud = cloud
        if local is not None:
            self.local = local

    @property
    def cloud(self):
        """Gets the cloud of this BucketNames.  # noqa: E501


        :return: The cloud of this BucketNames.  # noqa: E501
        :rtype: list[str]
        """
        return self._cloud

    @cloud.setter
    def cloud(self, cloud):
        """Sets the cloud of this BucketNames.


        :param cloud: The cloud of this BucketNames.  # noqa: E501
        :type: list[str]
        """

        self._cloud = cloud

    @property
    def local(self):
        """Gets the local of this BucketNames.  # noqa: E501


        :return: The local of this BucketNames.  # noqa: E501
        :rtype: list[str]
        """
        return self._local

    @local.setter
    def local(self, local):
        """Sets the local of this BucketNames.


        :param local: The local of this BucketNames.  # noqa: E501
        :type: list[str]
        """

        self._local = local

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BucketNames):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
