# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DaemonConfigurationLog(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'logdir': 'str',
        'loglevel': 'str',
        'logmaxsize': 'int',
        'logmaxtotal': 'int'
    }

    attribute_map = {
        'logdir': 'logdir',
        'loglevel': 'loglevel',
        'logmaxsize': 'logmaxsize',
        'logmaxtotal': 'logmaxtotal'
    }

    def __init__(self, logdir=None, loglevel=None, logmaxsize=None, logmaxtotal=None):  # noqa: E501
        """DaemonConfigurationLog - a model defined in OpenAPI"""  # noqa: E501

        self._logdir = None
        self._loglevel = None
        self._logmaxsize = None
        self._logmaxtotal = None
        self.discriminator = None

        if logdir is not None:
            self.logdir = logdir
        if loglevel is not None:
            self.loglevel = loglevel
        if logmaxsize is not None:
            self.logmaxsize = logmaxsize
        if logmaxtotal is not None:
            self.logmaxtotal = logmaxtotal

    @property
    def logdir(self):
        """Gets the logdir of this DaemonConfigurationLog.  # noqa: E501


        :return: The logdir of this DaemonConfigurationLog.  # noqa: E501
        :rtype: str
        """
        return self._logdir

    @logdir.setter
    def logdir(self, logdir):
        """Sets the logdir of this DaemonConfigurationLog.


        :param logdir: The logdir of this DaemonConfigurationLog.  # noqa: E501
        :type: str
        """

        self._logdir = logdir

    @property
    def loglevel(self):
        """Gets the loglevel of this DaemonConfigurationLog.  # noqa: E501


        :return: The loglevel of this DaemonConfigurationLog.  # noqa: E501
        :rtype: str
        """
        return self._loglevel

    @loglevel.setter
    def loglevel(self, loglevel):
        """Sets the loglevel of this DaemonConfigurationLog.


        :param loglevel: The loglevel of this DaemonConfigurationLog.  # noqa: E501
        :type: str
        """

        self._loglevel = loglevel

    @property
    def logmaxsize(self):
        """Gets the logmaxsize of this DaemonConfigurationLog.  # noqa: E501


        :return: The logmaxsize of this DaemonConfigurationLog.  # noqa: E501
        :rtype: int
        """
        return self._logmaxsize

    @logmaxsize.setter
    def logmaxsize(self, logmaxsize):
        """Sets the logmaxsize of this DaemonConfigurationLog.


        :param logmaxsize: The logmaxsize of this DaemonConfigurationLog.  # noqa: E501
        :type: int
        """

        self._logmaxsize = logmaxsize

    @property
    def logmaxtotal(self):
        """Gets the logmaxtotal of this DaemonConfigurationLog.  # noqa: E501


        :return: The logmaxtotal of this DaemonConfigurationLog.  # noqa: E501
        :rtype: int
        """
        return self._logmaxtotal

    @logmaxtotal.setter
    def logmaxtotal(self, logmaxtotal):
        """Sets the logmaxtotal of this DaemonConfigurationLog.


        :param logmaxtotal: The logmaxtotal of this DaemonConfigurationLog.  # noqa: E501
        :type: int
        """

        self._logmaxtotal = logmaxtotal

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DaemonConfigurationLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
