# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DaemonConfigurationCallstats(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'request_included': 'list[str]',
        'factor': 'float'
    }

    attribute_map = {
        'request_included': 'request_included',
        'factor': 'factor'
    }

    def __init__(self, request_included=None, factor=None):  # noqa: E501
        """DaemonConfigurationCallstats - a model defined in OpenAPI"""  # noqa: E501

        self._request_included = None
        self._factor = None
        self.discriminator = None

        if request_included is not None:
            self.request_included = request_included
        if factor is not None:
            self.factor = factor

    @property
    def request_included(self):
        """Gets the request_included of this DaemonConfigurationCallstats.  # noqa: E501


        :return: The request_included of this DaemonConfigurationCallstats.  # noqa: E501
        :rtype: list[str]
        """
        return self._request_included

    @request_included.setter
    def request_included(self, request_included):
        """Sets the request_included of this DaemonConfigurationCallstats.


        :param request_included: The request_included of this DaemonConfigurationCallstats.  # noqa: E501
        :type: list[str]
        """

        self._request_included = request_included

    @property
    def factor(self):
        """Gets the factor of this DaemonConfigurationCallstats.  # noqa: E501


        :return: The factor of this DaemonConfigurationCallstats.  # noqa: E501
        :rtype: float
        """
        return self._factor

    @factor.setter
    def factor(self, factor):
        """Sets the factor of this DaemonConfigurationCallstats.


        :param factor: The factor of this DaemonConfigurationCallstats.  # noqa: E501
        :type: float
        """

        self._factor = factor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DaemonConfigurationCallstats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
