# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DaemonInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'daemon_id': 'str',
        'public_net': 'NetInfo',
        'internal_net': 'NetInfo',
        'repl_net': 'NetInfo'
    }

    attribute_map = {
        'daemon_id': 'daemon_id',
        'public_net': 'public_net',
        'internal_net': 'internal_net',
        'repl_net': 'repl_net'
    }

    def __init__(self, daemon_id=None, public_net=None, internal_net=None, repl_net=None):  # noqa: E501
        """DaemonInfo - a model defined in OpenAPI"""  # noqa: E501

        self._daemon_id = None
        self._public_net = None
        self._internal_net = None
        self._repl_net = None
        self.discriminator = None

        if daemon_id is not None:
            self.daemon_id = daemon_id
        if public_net is not None:
            self.public_net = public_net
        if internal_net is not None:
            self.internal_net = internal_net
        if repl_net is not None:
            self.repl_net = repl_net

    @property
    def daemon_id(self):
        """Gets the daemon_id of this DaemonInfo.  # noqa: E501


        :return: The daemon_id of this DaemonInfo.  # noqa: E501
        :rtype: str
        """
        return self._daemon_id

    @daemon_id.setter
    def daemon_id(self, daemon_id):
        """Sets the daemon_id of this DaemonInfo.


        :param daemon_id: The daemon_id of this DaemonInfo.  # noqa: E501
        :type: str
        """

        self._daemon_id = daemon_id

    @property
    def public_net(self):
        """Gets the public_net of this DaemonInfo.  # noqa: E501


        :return: The public_net of this DaemonInfo.  # noqa: E501
        :rtype: NetInfo
        """
        return self._public_net

    @public_net.setter
    def public_net(self, public_net):
        """Sets the public_net of this DaemonInfo.


        :param public_net: The public_net of this DaemonInfo.  # noqa: E501
        :type: NetInfo
        """

        self._public_net = public_net

    @property
    def internal_net(self):
        """Gets the internal_net of this DaemonInfo.  # noqa: E501


        :return: The internal_net of this DaemonInfo.  # noqa: E501
        :rtype: NetInfo
        """
        return self._internal_net

    @internal_net.setter
    def internal_net(self, internal_net):
        """Sets the internal_net of this DaemonInfo.


        :param internal_net: The internal_net of this DaemonInfo.  # noqa: E501
        :type: NetInfo
        """

        self._internal_net = internal_net

    @property
    def repl_net(self):
        """Gets the repl_net of this DaemonInfo.  # noqa: E501


        :return: The repl_net of this DaemonInfo.  # noqa: E501
        :rtype: NetInfo
        """
        return self._repl_net

    @repl_net.setter
    def repl_net(self, repl_net):
        """Sets the repl_net of this DaemonInfo.


        :param repl_net: The repl_net of this DaemonInfo.  # noqa: E501
        :type: NetInfo
        """

        self._repl_net = repl_net

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DaemonInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
