# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DaemonConfigurationProxyconfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'primary': 'ProxyConfiguration',
        'original': 'ProxyConfiguration'
    }

    attribute_map = {
        'primary': 'primary',
        'original': 'original'
    }

    def __init__(self, primary=None, original=None):  # noqa: E501
        """DaemonConfigurationProxyconfig - a model defined in OpenAPI"""  # noqa: E501

        self._primary = None
        self._original = None
        self.discriminator = None

        if primary is not None:
            self.primary = primary
        if original is not None:
            self.original = original

    @property
    def primary(self):
        """Gets the primary of this DaemonConfigurationProxyconfig.  # noqa: E501


        :return: The primary of this DaemonConfigurationProxyconfig.  # noqa: E501
        :rtype: ProxyConfiguration
        """
        return self._primary

    @primary.setter
    def primary(self, primary):
        """Sets the primary of this DaemonConfigurationProxyconfig.


        :param primary: The primary of this DaemonConfigurationProxyconfig.  # noqa: E501
        :type: ProxyConfiguration
        """

        self._primary = primary

    @property
    def original(self):
        """Gets the original of this DaemonConfigurationProxyconfig.  # noqa: E501


        :return: The original of this DaemonConfigurationProxyconfig.  # noqa: E501
        :rtype: ProxyConfiguration
        """
        return self._original

    @original.setter
    def original(self, original):
        """Sets the original of this DaemonConfigurationProxyconfig.


        :param original: The original of this DaemonConfigurationProxyconfig.  # noqa: E501
        :type: ProxyConfiguration
        """

        self._original = original

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DaemonConfigurationProxyconfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
