# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DaemonConfigurationPeriodic(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'stats_time': 'str',
        'retry_sync_time': 'str'
    }

    attribute_map = {
        'stats_time': 'stats_time',
        'retry_sync_time': 'retry_sync_time'
    }

    def __init__(self, stats_time=None, retry_sync_time=None):  # noqa: E501
        """DaemonConfigurationPeriodic - a model defined in OpenAPI"""  # noqa: E501

        self._stats_time = None
        self._retry_sync_time = None
        self.discriminator = None

        if stats_time is not None:
            self.stats_time = stats_time
        if retry_sync_time is not None:
            self.retry_sync_time = retry_sync_time

    @property
    def stats_time(self):
        """Gets the stats_time of this DaemonConfigurationPeriodic.  # noqa: E501


        :return: The stats_time of this DaemonConfigurationPeriodic.  # noqa: E501
        :rtype: str
        """
        return self._stats_time

    @stats_time.setter
    def stats_time(self, stats_time):
        """Sets the stats_time of this DaemonConfigurationPeriodic.


        :param stats_time: The stats_time of this DaemonConfigurationPeriodic.  # noqa: E501
        :type: str
        """

        self._stats_time = stats_time

    @property
    def retry_sync_time(self):
        """Gets the retry_sync_time of this DaemonConfigurationPeriodic.  # noqa: E501


        :return: The retry_sync_time of this DaemonConfigurationPeriodic.  # noqa: E501
        :rtype: str
        """
        return self._retry_sync_time

    @retry_sync_time.setter
    def retry_sync_time(self, retry_sync_time):
        """Sets the retry_sync_time of this DaemonConfigurationPeriodic.


        :param retry_sync_time: The retry_sync_time of this DaemonConfigurationPeriodic.  # noqa: E501
        :type: str
        """

        self._retry_sync_time = retry_sync_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DaemonConfigurationPeriodic):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
