# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InputParameters(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'action': 'Actions',
        'name': 'str',
        'value': 'object'
    }

    attribute_map = {
        'action': 'action',
        'name': 'name',
        'value': 'value'
    }

    def __init__(self, action=None, name=None, value=None):  # noqa: E501
        """InputParameters - a model defined in OpenAPI"""  # noqa: E501

        self._action = None
        self._name = None
        self._value = None
        self.discriminator = None

        if action is not None:
            self.action = action
        if name is not None:
            self.name = name
        if value is not None:
            self.value = value

    @property
    def action(self):
        """Gets the action of this InputParameters.  # noqa: E501


        :return: The action of this InputParameters.  # noqa: E501
        :rtype: Actions
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this InputParameters.


        :param action: The action of this InputParameters.  # noqa: E501
        :type: Actions
        """

        self._action = action

    @property
    def name(self):
        """Gets the name of this InputParameters.  # noqa: E501


        :return: The name of this InputParameters.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InputParameters.


        :param name: The name of this InputParameters.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """Gets the value of this InputParameters.  # noqa: E501


        :return: The value of this InputParameters.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this InputParameters.


        :param value: The value of this InputParameters.  # noqa: E501
        :type: object
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InputParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
