# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class KeepAliveTrackerConfiguration(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'interval': 'str',
        'name': 'str',
        'max': 'str',
        'factor': 'int'
    }

    attribute_map = {
        'interval': 'interval',
        'name': 'name',
        'max': 'max',
        'factor': 'factor'
    }

    def __init__(self, interval=None, name=None, max=None, factor=None):  # noqa: E501
        """KeepAliveTrackerConfiguration - a model defined in OpenAPI"""  # noqa: E501

        self._interval = None
        self._name = None
        self._max = None
        self._factor = None
        self.discriminator = None

        if interval is not None:
            self.interval = interval
        if name is not None:
            self.name = name
        if max is not None:
            self.max = max
        if factor is not None:
            self.factor = factor

    @property
    def interval(self):
        """Gets the interval of this KeepAliveTrackerConfiguration.  # noqa: E501


        :return: The interval of this KeepAliveTrackerConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this KeepAliveTrackerConfiguration.


        :param interval: The interval of this KeepAliveTrackerConfiguration.  # noqa: E501
        :type: str
        """

        self._interval = interval

    @property
    def name(self):
        """Gets the name of this KeepAliveTrackerConfiguration.  # noqa: E501


        :return: The name of this KeepAliveTrackerConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this KeepAliveTrackerConfiguration.


        :param name: The name of this KeepAliveTrackerConfiguration.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def max(self):
        """Gets the max of this KeepAliveTrackerConfiguration.  # noqa: E501


        :return: The max of this KeepAliveTrackerConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._max

    @max.setter
    def max(self, max):
        """Sets the max of this KeepAliveTrackerConfiguration.


        :param max: The max of this KeepAliveTrackerConfiguration.  # noqa: E501
        :type: str
        """

        self._max = max

    @property
    def factor(self):
        """Gets the factor of this KeepAliveTrackerConfiguration.  # noqa: E501


        :return: The factor of this KeepAliveTrackerConfiguration.  # noqa: E501
        :rtype: int
        """
        return self._factor

    @factor.setter
    def factor(self, factor):
        """Sets the factor of this KeepAliveTrackerConfiguration.


        :param factor: The factor of this KeepAliveTrackerConfiguration.  # noqa: E501
        :type: int
        """

        self._factor = factor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KeepAliveTrackerConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
