# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ObjectPropertyList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'pagemarker': 'str',
        'entries': 'list[ObjectProperties]'
    }

    attribute_map = {
        'pagemarker': 'pagemarker',
        'entries': 'entries'
    }

    def __init__(self, pagemarker=None, entries=None):  # noqa: E501
        """ObjectPropertyList - a model defined in OpenAPI"""  # noqa: E501

        self._pagemarker = None
        self._entries = None
        self.discriminator = None

        if pagemarker is not None:
            self.pagemarker = pagemarker
        if entries is not None:
            self.entries = entries

    @property
    def pagemarker(self):
        """Gets the pagemarker of this ObjectPropertyList.  # noqa: E501


        :return: The pagemarker of this ObjectPropertyList.  # noqa: E501
        :rtype: str
        """
        return self._pagemarker

    @pagemarker.setter
    def pagemarker(self, pagemarker):
        """Sets the pagemarker of this ObjectPropertyList.


        :param pagemarker: The pagemarker of this ObjectPropertyList.  # noqa: E501
        :type: str
        """

        self._pagemarker = pagemarker

    @property
    def entries(self):
        """Gets the entries of this ObjectPropertyList.  # noqa: E501


        :return: The entries of this ObjectPropertyList.  # noqa: E501
        :rtype: list[ObjectProperties]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this ObjectPropertyList.


        :param entries: The entries of this ObjectPropertyList.  # noqa: E501
        :type: list[ObjectProperties]
        """

        self._entries = entries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObjectPropertyList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
