# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PrefetchTargetStatistics(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'xaction_details': 'list[XactionDetails]',
        'num_files_prefetched': 'int',
        'num_bytes_prefetched': 'int'
    }

    attribute_map = {
        'xaction_details': 'xactionDetails',
        'num_files_prefetched': 'numFilesPrefetched',
        'num_bytes_prefetched': 'numBytesPrefetched'
    }

    def __init__(self, xaction_details=None, num_files_prefetched=None, num_bytes_prefetched=None):  # noqa: E501
        """PrefetchTargetStatistics - a model defined in OpenAPI"""  # noqa: E501

        self._xaction_details = None
        self._num_files_prefetched = None
        self._num_bytes_prefetched = None
        self.discriminator = None

        if xaction_details is not None:
            self.xaction_details = xaction_details
        if num_files_prefetched is not None:
            self.num_files_prefetched = num_files_prefetched
        if num_bytes_prefetched is not None:
            self.num_bytes_prefetched = num_bytes_prefetched

    @property
    def xaction_details(self):
        """Gets the xaction_details of this PrefetchTargetStatistics.  # noqa: E501


        :return: The xaction_details of this PrefetchTargetStatistics.  # noqa: E501
        :rtype: list[XactionDetails]
        """
        return self._xaction_details

    @xaction_details.setter
    def xaction_details(self, xaction_details):
        """Sets the xaction_details of this PrefetchTargetStatistics.


        :param xaction_details: The xaction_details of this PrefetchTargetStatistics.  # noqa: E501
        :type: list[XactionDetails]
        """

        self._xaction_details = xaction_details

    @property
    def num_files_prefetched(self):
        """Gets the num_files_prefetched of this PrefetchTargetStatistics.  # noqa: E501


        :return: The num_files_prefetched of this PrefetchTargetStatistics.  # noqa: E501
        :rtype: int
        """
        return self._num_files_prefetched

    @num_files_prefetched.setter
    def num_files_prefetched(self, num_files_prefetched):
        """Sets the num_files_prefetched of this PrefetchTargetStatistics.


        :param num_files_prefetched: The num_files_prefetched of this PrefetchTargetStatistics.  # noqa: E501
        :type: int
        """

        self._num_files_prefetched = num_files_prefetched

    @property
    def num_bytes_prefetched(self):
        """Gets the num_bytes_prefetched of this PrefetchTargetStatistics.  # noqa: E501


        :return: The num_bytes_prefetched of this PrefetchTargetStatistics.  # noqa: E501
        :rtype: int
        """
        return self._num_bytes_prefetched

    @num_bytes_prefetched.setter
    def num_bytes_prefetched(self, num_bytes_prefetched):
        """Sets the num_bytes_prefetched of this PrefetchTargetStatistics.


        :param num_bytes_prefetched: The num_bytes_prefetched of this PrefetchTargetStatistics.  # noqa: E501
        :type: int
        """

        self._num_bytes_prefetched = num_bytes_prefetched

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrefetchTargetStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
