# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# and
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/deploy/prod/k8s/aisnode_container/"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/python/"
    labels:
      - "dependencies"
      - "dependabot"
    schedule:
      interval: "monthly"
