# coding: utf-8

"""
    AIS

    AIStore is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    The version of the OpenAPI document: 3.0
    Contact: aisdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "ais-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="AIS",
    author="NVIDIA-AIS",
    author_email="aisdev@exchange.nvidia.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "AIS"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description="""\
    AIStore is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501
    """
)
