version: "2"

linters:
  default: standard  ## TODO: 'none|standard|all'; enable
  disable:
    - errcheck
    - gosec
  enable:
    - asciicheck
    - bodyclose
    - canonicalheader
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    # errcheck
    # errorlint   ## TODO (wrapped errors; non-wrapping)
    - fatcontext
    - gochecksumtype
    - gocritic
    - goheader
    - gomoddirectives
    - goprintffuncname
    # gosec
    - govet
    - importas
    - ineffassign
    - intrange
    - musttag
    - misspell
    - nakedret
    - nilnesserr
    - nolintlint
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - revive
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - usetesting
    - wastedassign
    - whitespace

# See: https://golangci-lint.run/usage/linters/
  settings:
    dupl:
      threshold: 100

    revive:
      # ignore-generated-header: true
      severity: warning
      rules:
        # name: import-shadowing ## (e.g., url)
        # name: unhandled-error  ## TODO (wtp)
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: early-return
        - name: error-naming
        - name: error-strings
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: modifies-value-receiver
        # name: package-comments  TODO (wtp)
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: string-of-int
        - name: superfluous-else
        - name: time-naming
        - name: var-naming
        - name: var-declaration
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: waitgroup-by-value

    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: false
      # exclude-functions:
        # io/ioutil.ReadFile
        # io.Copy(*bytes.Buffer)
        # io.Copy(os.Stdout)

    govet:
      enable-all: true
      disable:
        - fieldalignment ## TODO (wtp)
        - shadow         ## ditto

    gocritic:
      enabled-tags:
        - performance
        - style
      disabled-checks:
        - unnamedResult
        - unnecessaryBlock
        - importShadow   ## TODO (wtp)

    gosec:
      excludes: ## integer overflow; weak rand
        - G115
        - G402
        - G404

    prealloc:
      simple: true # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them
      range-loops: true # Report preallocation suggestions on range loops, true by default
      for-loops: true # Report preallocation suggestions on for loops, false by default

    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Default is to use a neutral variety of English.
      # Setting locale to US will correct the British spelling of 'colour' to 'color'.
      locale: US

    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
            - pkg: 'math/rand$'
              desc: "`math/rand` package has been deprecated use `math/rand/v2`"

  # Defines a set of rules to ignore issues.
  # It does not skip the analysis, and so does not ignore "typecheck" errors.
  exclusions:
    warn-unused: false ## TODO (e.g., warn skipped [Path: "tools/", Linters: "nakedret"])
    # Predefined exclusion rules.
    # Default: []
    presets:
      # comments
      # std-error-handling
      # common-false-positives
      - legacy

    # Excluding configuration per-path, per-linter, per-text and per-source.
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - errcheck
          - dupl
          - gosec
          - nakedret
      - path: bench/
        linters:
          - nakedret
      - path: tools/
        linters:
          - nakedret

      # Exclude some `staticcheck` messages.
      - linters:
          - staticcheck
        text: "QF1008:"
      # linters:
      #   - staticcheck
      # text: "ST1005:"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    goimports:
      local-prefixes:
        - github.com/NVIDIA/aistore
  # exclusions:
    # paths:
      # test/testdata

run:
  go: '1.24'
  tests: true # Enable linting test files.
  concurrency: 8
  timeout: 8m

    # NOTE: these are the default build tags for the linter;
    # use `TAGS=... make lint` to check that the corresponding alternative sources do lint correctly;
    # e.g. `TAGS=statsd make lint`
  build-tags:
    - hrw
    - aws
    - azure
    - gcp
    - oci
    # - nethttp
    # - statsd

