linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - canonicalheader
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - fatcontext
    - gci
    - gochecksumtype
    - gocritic
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - intrange
    - misspell
    - nolintlint
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - revive
    - staticcheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

# See: https://golangci-lint.run/usage/linters/
linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      # name: import-shadowing ## TODO: enable
      # name: unhandled-error
      # name: line-length-limit
      # name: dot-imports
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: early-return
      - name: error-naming
      - name: error-strings
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      - name: superfluous-else
      - name: time-naming
      - name: var-naming
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver
      - name: waitgroup-by-value
  gci:
    skip-generated: true
  govet:
    enable-all: true
    disable:
      - fieldalignment # TODO: enable once in a while (lots of noise though)
      - shadow # Reports a lot of false-positives and conflicts with other linters.
  errcheck:
    check-blank: true
    check-type-assertions: false
  gocritic:
    enabled-tags:
      - performance
      - style
    disabled-checks:
      - ifElseChain ## TODO: enable
      - unnamedResult
  gosec:
    excludes: ## integer overflow; week rand
      - G115
      - G402
      - G404
  prealloc:
    simple: true # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: true # Report preallocation suggestions on for loops, false by default
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
  depguard:
    rules:
      main:
        deny:
          - pkg: 'math/rand$'
            desc: "`math/rand` package has been deprecated use `math/rand/v2`"

issues:
  # use default exclude rules
  exclude-use-default: true

  # additional exclude rules
  exclude-rules:
    - linters: [errcheck]
      text: "Error return value of" # ignores 'error return value of ... is unchecked'

    - linters: [golint]
      text: "and that stutters; consider calling this"

    - linters: [golint]
      text: "don't use an underscore in package name"

    - linters: [revive]
      text: "or a comment on this block"

    - linters: [unused]
      text: "`noCopy` is unused"

    - linters: [gocritic]
      text: "importShadow: shadow of imported"

    - linters: [gocritic]
      text: "builtinShadow: shadowing of predeclared identifier: new"

    - linters: [gocritic, gofmt, goimports]
      source: "///" # commentFormatting

    - linters: [gocritic, gofmt, goimports]
      source: "//==" # commentFormatting

    - linters: [staticcheck]
      text: "SA5011:" # produces a lot of false-positives; hopefully in the future we could enable it!

    - linters: [interfacer]
      text: "k8s.io/client-go/rest.HTTPClient" # suggests to change `*http.Client` to `rest.HTTPClient`...

    - linters: [staticcheck]
      text: "SA3000: TestMain should call os.Exit to set exit code" # This is not true for Go1.15 or later.

    - linters: [gocritic]
      text: "block doesn't have definitions" # Sometimes blocks are useful for better readability.

    - linters: [golint]
      source: "embed" # Justification for `import _ "embed"` is not needed.

  # Set to 0 to disable limit
  max-same-issues: 0
  max-issues-per-linter: 0

run:
  go: '1.23.2'
  tests: true # Enable linting test files.
  concurrency: 4
  timeout: 6m

    # NOTE: these are the default build tags for the linter;
    # use `TAGS=... make lint` to check that the corresponding alternative sources do lint correctly;
    # e.g. `TAGS=statsd make lint`
  build-tags:
    - hrw
    - aws
    - azure
    - gcp
    # - nethttp
    # - statsd

