linters:
  enable-all: false
  disable-all: true
  enable:
    - revive
    - asciicheck
    - bodyclose
    - deadcode
    - durationcheck
    - errcheck
    - exportloopref
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

    # See: https://golangci-lint.run/usage/linters/
    #
    # TODO: Following linters should be enabled at some:
    # - ifshort
    # - nilerr
    #
    # Following linters produce false positives (enable only when needed):
    # - goconst
    # - godot
    # - goerr113
    # - gosec
    # - nestif
    # - scopelint
    # - structcheck - doesn't handle embedded structs
    #
    # Following linters are not really helpful:
    # - cyclop
    # - exhaustive
    # - forbidigo
    # - forcetypeassert
    # - interfacer
    # - nlreturn
    # - noctx
    # - predeclared
    # - testpackage
    # - thelper
    # - tparallel
    # - wrapcheck

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      # name: early-return
      # name: import-shadowing
      # name: unhandled-error
      # name: unused-parameter
      # name: unused-receiver
      # arguments : ["fmt.Printf", "fmt.Fprintf", "fmt.Fprintln"]
      # name: line-length-limit
      # severity: error
      # arguments: [130]
      - name: if-return
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-naming
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: imports-blacklist
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      - name: superfluous-else
      - name: time-naming
      - name: var-naming
      - name: var-declaration
      - name: unconditional-recursion
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: waitgroup-by-value
  govet:
    enable-all: true
    disable:
      - fieldalignment # TODO: Enable, for now reports a lot of problems.
      - shadow # Reports a lot of false-positives and conflicts with other linters.
    settings:
      printf: # Analyzer name, run `go tool vet help` to see all analyzers.
        funcs: # Run `go tool vet help printf` to see available settings for `printf` analyzer.
          - github.com/NVIDIA/aistore/3rdparty/glog.Infof
          - github.com/NVIDIA/aistore/3rdparty/glog.Warningf
          - github.com/NVIDIA/aistore/3rdparty/glog.Errorf
          - github.com/NVIDIA/aistore/3rdparty/glog.Fatalf
          - github.com/NVIDIA/aistore/cmn/debug.Assertf
          - github.com/NVIDIA/aistore/cmn/debug.Errorf
          - github.com/NVIDIA/aistore/cmn/debug.Infof
          - github.com/NVIDIA/aistore/cmn/cos.Exitf
          - github.com/NVIDIA/aistore/cmn/cos.ExitLogf
  golint:
    min-confidence: 0
  errcheck:
    check-blank: true
    check-type-assertions: false
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - ifElseChain
      - hugeParam # produces a lot of false-positives (TODO: see if some errors are possible improvements)
      - unnamedResult
  prealloc:
    simple: true # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: true # Report preallocation suggestions on for loops, false by default
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US

issues:
  # use default exclude rules
  exclude-use-default: true

  # additional exclude rules
  exclude-rules:
    - linters: errcheck
      text: "Error return value of" # ignores 'error return value of ... is unchecked'

    - linters: golint
      text: "and that stutters; consider calling this"

    - linters: golint
      text: "don't use an underscore in package name"

    - linters: unused
      text: "`noCopy` is unused"

    - linters: gocritic
      text: "importShadow: shadow of imported"

    - linters: gocritic
      text: "builtinShadow: shadowing of predeclared identifier: new"

    - linters: gocritic
      source: "///" # commentFormatting

    - linters: gocritic
      source: "//==" # commentFormatting

    - linters: staticcheck
      text: "SA5011:" # produces a lot of false-positives; hopefully in the future we could enable it!

    - linters: interfacer
      text: "k8s.io/client-go/rest.HTTPClient" # suggests to change `*http.Client` to `rest.HTTPClient`...

    - linters: staticcheck
      text: "SA3000: TestMain should call os.Exit to set exit code" # This is not true for Go1.15 or later.

    - linters: gocritic
      text: "block doesn't have definitions" # Sometimes blocks are useful for better readability.

    - linters: golint
      source: "embed" # Justification for `import _ "embed"` is not needed.

  # Set to 0 to disable limit
  max-same-issues: 0
  max-per-linter: 0

run:
  tests: true # enable linting test files

  build-tags:
    - hrw aws azure gcp hdfs # Build hrw and backend providers so that staticcheck doesn't complain about unused export functions.

  concurrency: 4
  deadline: 5m
