package sys

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *MemStat) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "t":
			z.Total, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Total")
				return
			}
		case "u":
			z.Used, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Used")
				return
			}
		case "f":
			z.Free, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Free")
				return
			}
		case "b":
			z.BuffCache, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "BuffCache")
				return
			}
		case "af":
			z.ActualFree, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ActualFree")
				return
			}
		case "au":
			z.ActualUsed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "ActualUsed")
				return
			}
		case "st":
			z.SwapTotal, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "SwapTotal")
				return
			}
		case "sf":
			z.SwapFree, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "SwapFree")
				return
			}
		case "su":
			z.SwapUsed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "SwapUsed")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MemStat) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 9
	// write "t"
	err = en.Append(0x89, 0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Total)
	if err != nil {
		err = msgp.WrapError(err, "Total")
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Used)
	if err != nil {
		err = msgp.WrapError(err, "Used")
		return
	}
	// write "f"
	err = en.Append(0xa1, 0x66)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Free)
	if err != nil {
		err = msgp.WrapError(err, "Free")
		return
	}
	// write "b"
	err = en.Append(0xa1, 0x62)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.BuffCache)
	if err != nil {
		err = msgp.WrapError(err, "BuffCache")
		return
	}
	// write "af"
	err = en.Append(0xa2, 0x61, 0x66)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.ActualFree)
	if err != nil {
		err = msgp.WrapError(err, "ActualFree")
		return
	}
	// write "au"
	err = en.Append(0xa2, 0x61, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.ActualUsed)
	if err != nil {
		err = msgp.WrapError(err, "ActualUsed")
		return
	}
	// write "st"
	err = en.Append(0xa2, 0x73, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.SwapTotal)
	if err != nil {
		err = msgp.WrapError(err, "SwapTotal")
		return
	}
	// write "sf"
	err = en.Append(0xa2, 0x73, 0x66)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.SwapFree)
	if err != nil {
		err = msgp.WrapError(err, "SwapFree")
		return
	}
	// write "su"
	err = en.Append(0xa2, 0x73, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.SwapUsed)
	if err != nil {
		err = msgp.WrapError(err, "SwapUsed")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MemStat) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 3 + msgp.Uint64Size + 3 + msgp.Uint64Size + 3 + msgp.Uint64Size + 3 + msgp.Uint64Size + 3 + msgp.Uint64Size
	return
}
