package sys

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *ProcCPUStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "u":
			z.User, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "User")
				return
			}
		case "s":
			z.System, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "System")
				return
			}
		case "t":
			z.Total, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Total")
				return
			}
		case "l":
			z.LastTime, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "LastTime")
				return
			}
		case "p":
			z.Percent, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Percent")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ProcCPUStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "u"
	err = en.Append(0x85, 0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.User)
	if err != nil {
		err = msgp.WrapError(err, "User")
		return
	}
	// write "s"
	err = en.Append(0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.System)
	if err != nil {
		err = msgp.WrapError(err, "System")
		return
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Total)
	if err != nil {
		err = msgp.WrapError(err, "Total")
		return
	}
	// write "l"
	err = en.Append(0xa1, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.LastTime)
	if err != nil {
		err = msgp.WrapError(err, "LastTime")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.Percent)
	if err != nil {
		err = msgp.WrapError(err, "Percent")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ProcCPUStats) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Int64Size + 2 + msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ProcMemStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "s":
			z.Size, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "r":
			z.Resident, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Resident")
				return
			}
		case "h":
			z.Share, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Share")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ProcMemStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "s"
	err = en.Append(0x83, 0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Size)
	if err != nil {
		err = msgp.WrapError(err, "Size")
		return
	}
	// write "r"
	err = en.Append(0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Resident)
	if err != nil {
		err = msgp.WrapError(err, "Resident")
		return
	}
	// write "h"
	err = en.Append(0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Share)
	if err != nil {
		err = msgp.WrapError(err, "Share")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ProcMemStats) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ProcStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			err = z.CPU.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "CPU")
				return
			}
		case "m":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Mem")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Mem")
					return
				}
				switch msgp.UnsafeString(field) {
				case "s":
					z.Mem.Size, err = dc.ReadUint64()
					if err != nil {
						err = msgp.WrapError(err, "Mem", "Size")
						return
					}
				case "r":
					z.Mem.Resident, err = dc.ReadUint64()
					if err != nil {
						err = msgp.WrapError(err, "Mem", "Resident")
						return
					}
				case "h":
					z.Mem.Share, err = dc.ReadUint64()
					if err != nil {
						err = msgp.WrapError(err, "Mem", "Share")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Mem")
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *ProcStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "c"
	err = en.Append(0x82, 0xa1, 0x63)
	if err != nil {
		return
	}
	err = z.CPU.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "CPU")
		return
	}
	// write "m"
	err = en.Append(0xa1, 0x6d)
	if err != nil {
		return
	}
	// map header, size 3
	// write "s"
	err = en.Append(0x83, 0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Mem.Size)
	if err != nil {
		err = msgp.WrapError(err, "Mem", "Size")
		return
	}
	// write "r"
	err = en.Append(0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Mem.Resident)
	if err != nil {
		err = msgp.WrapError(err, "Mem", "Resident")
		return
	}
	// write "h"
	err = en.Append(0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Mem.Share)
	if err != nil {
		err = msgp.WrapError(err, "Mem", "Share")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ProcStats) Msgsize() (s int) {
	s = 1 + 2 + z.CPU.Msgsize() + 2 + 1 + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size
	return
}
