{
 "title": "Performance",
 "time": { "from": "2023-11-22T22:01:30.723Z", "to": "2023-11-22T22:07:29.441Z" },
 "templating": {
  "list": [
   { "name": "ClusterPrefix", "query": "sjc4,sjc4-dev,sjc11" },
   { "name": "StoragePrefix", "query": "sd,nvme" },
   { "name": "NetInterface", "query": "ens4f0,ens1,ens2" },
   { "name": "LoaderPrefix", "query": "aistoredgx" }
  ]
 },
 "panels": [
  {
   "title": "Disk IO time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(averageSeries(netdata.${ClusterPrefix}*.disk_iotime), 'Read IO time')"
    },
    {
     "target": "alias(absolute(averageSeries(netdata.${ClusterPrefix}*.disk_iotime.${StoragePrefix}*.writes)), 'Write IO time')"
    }
   ]
  },
  {
   "title": "Disk Queued Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "target": "alias(absolute(averageSeries(netdata.${ClusterPrefix}*.disk_qops.${StoragePrefix}*.operations)), 'Average Queued IO')"
    }
   ]
  },
  {
   "title": "Disk Await",
   "type": "timeseries",
   "description": "Average await times reported by iostat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(averageSeries(netdata.${ClusterPrefix}*.disk_await.${StoragePrefix}*.reads), 'Disk Read Await')"
    },
    {
     "target": "alias(absolute(averageSeries(netdata.${ClusterPrefix}*.disk_await.${StoragePrefix}*.writes)), 'Disk Write Await')"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "description": "Average disk usage across all disks in the cluster",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(averageSeries(netdata.${ClusterPrefix}*.disk_util.${StoragePrefix}*.utilization), 'Cluster Disk Utilization')"
    }
   ]
  },
  {
   "title": "PUT Throughput Metrics",
   "type": "timeseries",
   "description": "Comparison of AISloader-reported throughput and netdata-reported disk and network throughput on a PUT benchmark against an AIS cluster",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(scale(sum(netdata.${ClusterPrefix}*.net.$NetInterface.received), 125), 'Network Received')"
    },
    {
     "target": "alias(scale(absolute(sum(netdata.${ClusterPrefix}*.disk.${StoragePrefix}*.writes)), 1024), 'Disk Writes')"
    },
    {
     "target": "alias(sum(stats.gauges.aisloader.${LoaderPrefix}*.put.throughput), 'AISLoader PUT')"
    },
    {
     "target": "alias(scale(absolute(sum(netdata.${ClusterPrefix}*.cgroup_k8s*.net_eth0.received)), 125), 'K8s Network Received')"
    }
   ]
  },
  {
   "title": "GET Throughput Metrics",
   "type": "timeseries",
   "description": "Comparison of AISloader-reported throughput and netdata-reported disk and network throughput on a GET benchmark against an AIS cluster",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(sum(stats.gauges.aisloader.${LoaderPrefix}*.get.throughput), 'AISLoader GET')"
    },
    {
     "target": "alias(sum(scale(absolute(netdata.${ClusterPrefix}*.net.$NetInterface.sent), 125)), 'Network Sent')"
    },
    {
     "target": "alias(sum(scale(absolute(netdata.${ClusterPrefix}*.disk.${StoragePrefix}*.reads), 1024)), 'Disk Read')"
    },
    {
     "target": "alias(sum(scale(absolute(netdata.${ClusterPrefix}*.cgroup_k8s*.net_eth0.sent), 125)), 'K8s Network Sent')"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(averageSeries(stats.*.aisloader.${LoaderPrefix}*.get.latency.mean), 'GET Latency')"
    },
    {
     "target": "alias(averageSeries(stats.*.aisloader.${LoaderPrefix}*.put.latency.mean), 'PUT Latency')"
    }
   ]
  }
 ]
}