{
 "title": "Performance",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Disk IO time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(averageSeries(netdata.aistorecpu*.disk_iotime.sd*.reads), 'Read IO time')"
    },
    {
     "target": "alias(absolute(averageSeries(netdata.aistorecpu*.disk_iotime.sd*.writes)), 'Write IO time')"
    }
   ]
  },
  {
   "title": "Disk Queued Ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "target": "alias(absolute(averageSeries(netdata.aistorecpu*.disk_qops.sd*.*)), 'Average Queued IO')"
    }
   ]
  },
  {
   "title": "Disk Await",
   "type": "timeseries",
   "description": "Average await times reported by iostat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(averageSeries(netdata.aistorecpu*.disk_await.sd*.reads), 'Disk Read Await')"
    },
    {
     "target": "alias(absolute(averageSeries(netdata.aistorecpu*.disk_await.sd*.writes)), 'Disk Write Await')"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "description": "Average disk usage across all disks in the cluster",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "averageSeries(alias(netdata.aistorecpu*.disk_*.sd*.utilization, 'Average Disk Utilization'))"
    }
   ]
  },
  {
   "title": "PUT Throughput Metrics",
   "type": "timeseries",
   "description": "Comparison of AISloader-reported throughput and netdata-reported disk and network throughput on a PUT benchmark against an AIS cluster",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(scale(sum(netdata.aistorecpu*.net.ens2.received), 125), 'Network Received')"
    },
    {
     "target": "alias(scale(absolute(sum(netdata.aistorecpu*.disk.sd*.writes)), 1024), 'Disk Writes')"
    },
    {
     "target": "alias(sum(stats.gauges.aisloader.*.put.throughput), 'AISLoader PUT')"
    }
   ]
  },
  {
   "title": "GET Throughput Metrics",
   "type": "timeseries",
   "description": "Comparison of AISloader-reported throughput and netdata-reported disk and network throughput on a GET benchmark against an AIS cluster",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "target": "alias(sum(stats.gauges.aisloader.*.get.throughput), 'AISLoader GET')"
    },
    {
     "target": "alias(sum(scale(absolute(netdata.aistorecpu*.net.ens2.sent), 125)), 'Network Sent')"
    },
    {
     "target": "alias(sum(scale(absolute(netdata.aistorecpu*.disk.sd*.reads), 1024)), 'Disk Read')"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.*.aisloader.aistoredgx5921-7d.get.latency.sum, 'GET Latency')"
    },
    {
     "target": "alias(stats.*.aisloader.aistoredgx5921-7d.put.latency.sum, 'PUT Latency')"
    }
   ]
  }
 ]
}