#
# Build a trivial container delivering aisnode and ais CLI
# binaries, prebuilt for Alpine containers to copy these
# from their Dockerfiles. This unlinks GTC Dockerfiles from
# our ais repo. Run from root of ais clone.

FROM golang:1.15-alpine

RUN apk upgrade --no-cache && \
  apk add --no-cache --virtual .build-deps \
    bash \
    lsof \
    git \
    sysstat \
    attr \
    make \
    util-linux \
  ;

ENV GOBIN $GOPATH/bin

COPY . $GOPATH/src/github.com/NVIDIA/aistore/
WORKDIR $GOPATH/src/github.com/NVIDIA/aistore

RUN AIS_CLD_PROVIDER="" make node
RUN make cli
ARG AIS_VERSION=unknown
RUN echo $AIS_VERSION > /repo.HEAD-rev

COPY deploy/prod/docker/gtc2020/config/cli-config.json /cli-config.json
