#
# Dockerfile to build an aisnode Docker image
#
FROM ubuntu:bionic
ARG start_script
RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y wget sysstat python-pip curl nodejs git iputils-ping netcat make coreutils
RUN apt-get install -y net-tools iproute2 tcptrack
RUN mkdir -p /usr/local/bin
RUN cd /opt && git clone git://github.com/etsy/statsd.git
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
COPY $start_script /ais_docker_start.sh
COPY ais_readiness.sh /ais_readiness.sh
RUN chmod a+x /ais_docker_start.sh /ais_readiness.sh
COPY aisnode /usr/local/bin/aisnode
COPY ais /usr/local/bin/ais
COPY xmeta /usr/local/bin/xmeta
COPY git-showbranch.out /
CMD ["bash", "-c", "./ais_docker_start.sh"]
