package apc

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/NVIDIA/aistore/sys"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *MemCPUInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "u":
			z.MemUsed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "MemUsed")
				return
			}
		case "a":
			z.MemAvail, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "MemAvail")
				return
			}
		case "p":
			z.PctMemUsed, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "PctMemUsed")
				return
			}
		case "c":
			z.PctCPUUsed, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "PctCPUUsed")
				return
			}
		case "l":
			err = z.LoadAvg.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "LoadAvg")
				return
			}
		case "t":
			z.CPUUtil, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CPUUtil")
				return
			}
		case "h":
			z.CPUThrottled, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "CPUThrottled")
				return
			}
		case "m":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Mem")
					return
				}
				z.Mem = nil
			} else {
				if z.Mem == nil {
					z.Mem = new(sys.MemStat)
				}
				err = z.Mem.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Mem")
					return
				}
			}
		case "r":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Proc")
					return
				}
				z.Proc = nil
			} else {
				if z.Proc == nil {
					z.Proc = new(sys.ProcStats)
				}
				err = z.Proc.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Proc")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *MemCPUInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// omitempty: check for empty values
	zb0001Len := uint32(9)
	var zb0001Mask uint16 /* 9 bits */
	if z.CPUThrottled == 0 {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.Mem == nil {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.Proc == nil {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if zb0001Len == 0 {
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.MemUsed)
	if err != nil {
		err = msgp.WrapError(err, "MemUsed")
		return
	}
	// write "a"
	err = en.Append(0xa1, 0x61)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.MemAvail)
	if err != nil {
		err = msgp.WrapError(err, "MemAvail")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.PctMemUsed)
	if err != nil {
		err = msgp.WrapError(err, "PctMemUsed")
		return
	}
	// write "c"
	err = en.Append(0xa1, 0x63)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.PctCPUUsed)
	if err != nil {
		err = msgp.WrapError(err, "PctCPUUsed")
		return
	}
	// write "l"
	err = en.Append(0xa1, 0x6c)
	if err != nil {
		return
	}
	err = z.LoadAvg.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "LoadAvg")
		return
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.CPUUtil)
	if err != nil {
		err = msgp.WrapError(err, "CPUUtil")
		return
	}
	if (zb0001Mask & 0x40) == 0 { // if not empty
		// write "h"
		err = en.Append(0xa1, 0x68)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.CPUThrottled)
		if err != nil {
			err = msgp.WrapError(err, "CPUThrottled")
			return
		}
	}
	if (zb0001Mask & 0x80) == 0 { // if not empty
		// write "m"
		err = en.Append(0xa1, 0x6d)
		if err != nil {
			return
		}
		if z.Mem == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Mem.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Mem")
				return
			}
		}
	}
	if (zb0001Mask & 0x100) == 0 { // if not empty
		// write "r"
		err = en.Append(0xa1, 0x72)
		if err != nil {
			return
		}
		if z.Proc == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Proc.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Proc")
				return
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *MemCPUInfo) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Float64Size + 2 + msgp.Float64Size + 2 + z.LoadAvg.Msgsize() + 2 + msgp.Int64Size + 2 + msgp.Int64Size + 2
	if z.Mem == nil {
		s += msgp.NilSize
	} else {
		s += z.Mem.Msgsize()
	}
	s += 2
	if z.Proc == nil {
		s += msgp.NilSize
	} else {
		s += z.Proc.Msgsize()
	}
	return
}
