package fs

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/NVIDIA/aistore/cmn/cos"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CDF) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "l":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Label")
					return
				}
				z.Label = cos.MountpathLabel(zb0002)
			}
		case "f":
			err = z.FS.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "FS")
				return
			}
		case "d":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Disks")
				return
			}
			if cap(z.Disks) >= int(zb0003) {
				z.Disks = (z.Disks)[:zb0003]
			} else {
				z.Disks = make([]string, zb0003)
			}
			for za0001 := range z.Disks {
				z.Disks[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Disks", za0001)
					return
				}
			}
		case "Capacity":
			var zb0004 uint32
			zb0004, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Capacity")
				return
			}
			for zb0004 > 0 {
				zb0004--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Capacity")
					return
				}
				switch msgp.UnsafeString(field) {
				case "u":
					z.Capacity.Used, err = dc.ReadUint64()
					if err != nil {
						err = msgp.WrapError(err, "Capacity", "Used")
						return
					}
				case "a":
					z.Capacity.Avail, err = dc.ReadUint64()
					if err != nil {
						err = msgp.WrapError(err, "Capacity", "Avail")
						return
					}
				case "p":
					z.Capacity.PctUsed, err = dc.ReadInt32()
					if err != nil {
						err = msgp.WrapError(err, "Capacity", "PctUsed")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Capacity")
						return
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CDF) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "l"
	err = en.Append(0x84, 0xa1, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString((string)(z.Label))
	if err != nil {
		err = msgp.WrapError(err, "Label")
		return
	}
	// write "f"
	err = en.Append(0xa1, 0x66)
	if err != nil {
		return
	}
	err = z.FS.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "FS")
		return
	}
	// write "d"
	err = en.Append(0xa1, 0x64)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Disks)))
	if err != nil {
		err = msgp.WrapError(err, "Disks")
		return
	}
	for za0001 := range z.Disks {
		err = en.WriteString(z.Disks[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Disks", za0001)
			return
		}
	}
	// write "Capacity"
	err = en.Append(0xa8, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79)
	if err != nil {
		return
	}
	// map header, size 3
	// write "u"
	err = en.Append(0x83, 0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Capacity.Used)
	if err != nil {
		err = msgp.WrapError(err, "Capacity", "Used")
		return
	}
	// write "a"
	err = en.Append(0xa1, 0x61)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Capacity.Avail)
	if err != nil {
		err = msgp.WrapError(err, "Capacity", "Avail")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.Capacity.PctUsed)
	if err != nil {
		err = msgp.WrapError(err, "Capacity", "PctUsed")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CDF) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len((string)(z.Label)) + 2 + z.FS.Msgsize() + 2 + msgp.ArrayHeaderSize
	for za0001 := range z.Disks {
		s += msgp.StringPrefixSize + len(z.Disks[za0001])
	}
	s += 9 + 1 + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Capacity) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "u":
			z.Used, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Used")
				return
			}
		case "a":
			z.Avail, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Avail")
				return
			}
		case "p":
			z.PctUsed, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PctUsed")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Capacity) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "u"
	err = en.Append(0x83, 0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Used)
	if err != nil {
		err = msgp.WrapError(err, "Used")
		return
	}
	// write "a"
	err = en.Append(0xa1, 0x61)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Avail)
	if err != nil {
		err = msgp.WrapError(err, "Avail")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PctUsed)
	if err != nil {
		err = msgp.WrapError(err, "PctUsed")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Capacity) Msgsize() (s int) {
	s = 1 + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Tcdf) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "m":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Mountpaths")
				return
			}
			if z.Mountpaths == nil {
				z.Mountpaths = make(map[string]*CDF, zb0002)
			} else if len(z.Mountpaths) > 0 {
				for key := range z.Mountpaths {
					delete(z.Mountpaths, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 *CDF
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Mountpaths")
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Mountpaths", za0001)
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(CDF)
					}
					err = za0002.DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Mountpaths", za0001)
						return
					}
				}
				z.Mountpaths[za0001] = za0002
			}
		case "e":
			z.CsErr, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CsErr")
				return
			}
		case "u":
			z.TotalUsed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TotalUsed")
				return
			}
		case "a":
			z.TotalAvail, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TotalAvail")
				return
			}
		case "x":
			z.PctMax, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PctMax")
				return
			}
		case "v":
			z.PctAvg, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PctAvg")
				return
			}
		case "n":
			z.PctMin, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PctMin")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Tcdf) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 7
	// write "m"
	err = en.Append(0x87, 0xa1, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Mountpaths)))
	if err != nil {
		err = msgp.WrapError(err, "Mountpaths")
		return
	}
	for za0001, za0002 := range z.Mountpaths {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Mountpaths")
			return
		}
		if za0002 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = za0002.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Mountpaths", za0001)
				return
			}
		}
	}
	// write "e"
	err = en.Append(0xa1, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.CsErr)
	if err != nil {
		err = msgp.WrapError(err, "CsErr")
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.TotalUsed)
	if err != nil {
		err = msgp.WrapError(err, "TotalUsed")
		return
	}
	// write "a"
	err = en.Append(0xa1, 0x61)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.TotalAvail)
	if err != nil {
		err = msgp.WrapError(err, "TotalAvail")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PctMax)
	if err != nil {
		err = msgp.WrapError(err, "PctMax")
		return
	}
	// write "v"
	err = en.Append(0xa1, 0x76)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PctAvg)
	if err != nil {
		err = msgp.WrapError(err, "PctAvg")
		return
	}
	// write "n"
	err = en.Append(0xa1, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PctMin)
	if err != nil {
		err = msgp.WrapError(err, "PctMin")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Tcdf) Msgsize() (s int) {
	s = 1 + 2 + msgp.MapHeaderSize
	if z.Mountpaths != nil {
		for za0001, za0002 := range z.Mountpaths {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001)
			if za0002 == nil {
				s += msgp.NilSize
			} else {
				s += za0002.Msgsize()
			}
		}
	}
	s += 2 + msgp.StringPrefixSize + len(z.CsErr) + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Int32Size + 2 + msgp.Int32Size + 2 + msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TcdfExt) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "AllDiskStats":
			err = z.AllDiskStats.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "AllDiskStats")
				return
			}
		case "m":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Mountpaths")
				return
			}
			if z.Mountpaths == nil {
				z.Mountpaths = make(map[string]*CDF, zb0002)
			} else if len(z.Mountpaths) > 0 {
				for key := range z.Mountpaths {
					delete(z.Mountpaths, key)
				}
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				var za0002 *CDF
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Mountpaths")
					return
				}
				if dc.IsNil() {
					err = dc.ReadNil()
					if err != nil {
						err = msgp.WrapError(err, "Mountpaths", za0001)
						return
					}
					za0002 = nil
				} else {
					if za0002 == nil {
						za0002 = new(CDF)
					}
					err = za0002.DecodeMsg(dc)
					if err != nil {
						err = msgp.WrapError(err, "Mountpaths", za0001)
						return
					}
				}
				z.Mountpaths[za0001] = za0002
			}
		case "e":
			z.CsErr, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "CsErr")
				return
			}
		case "u":
			z.TotalUsed, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TotalUsed")
				return
			}
		case "a":
			z.TotalAvail, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "TotalAvail")
				return
			}
		case "x":
			z.PctMax, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PctMax")
				return
			}
		case "v":
			z.PctAvg, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PctAvg")
				return
			}
		case "n":
			z.PctMin, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "PctMin")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TcdfExt) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "AllDiskStats"
	err = en.Append(0x88, 0xac, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x73)
	if err != nil {
		return
	}
	err = z.AllDiskStats.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "AllDiskStats")
		return
	}
	// write "m"
	err = en.Append(0xa1, 0x6d)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Mountpaths)))
	if err != nil {
		err = msgp.WrapError(err, "Mountpaths")
		return
	}
	for za0001, za0002 := range z.Mountpaths {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Mountpaths")
			return
		}
		if za0002 == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = za0002.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Mountpaths", za0001)
				return
			}
		}
	}
	// write "e"
	err = en.Append(0xa1, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.CsErr)
	if err != nil {
		err = msgp.WrapError(err, "CsErr")
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.TotalUsed)
	if err != nil {
		err = msgp.WrapError(err, "TotalUsed")
		return
	}
	// write "a"
	err = en.Append(0xa1, 0x61)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.TotalAvail)
	if err != nil {
		err = msgp.WrapError(err, "TotalAvail")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PctMax)
	if err != nil {
		err = msgp.WrapError(err, "PctMax")
		return
	}
	// write "v"
	err = en.Append(0xa1, 0x76)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PctAvg)
	if err != nil {
		err = msgp.WrapError(err, "PctAvg")
		return
	}
	// write "n"
	err = en.Append(0xa1, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.PctMin)
	if err != nil {
		err = msgp.WrapError(err, "PctMin")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TcdfExt) Msgsize() (s int) {
	s = 1 + 13 + z.AllDiskStats.Msgsize() + 2 + msgp.MapHeaderSize
	if z.Mountpaths != nil {
		for za0001, za0002 := range z.Mountpaths {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001)
			if za0002 == nil {
				s += msgp.NilSize
			} else {
				s += za0002.Msgsize()
			}
		}
	}
	s += 2 + msgp.StringPrefixSize + len(z.CsErr) + 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.Int32Size + 2 + msgp.Int32Size + 2 + msgp.Int32Size
	return
}
