#
# Dockerfile to build an AIS docker image in which we include a copy of
# your GOPATH tree. Must be run from the intended $GOPATH, ie something
# like:
#
# cd $GOPATH
# docker build -f blah/blah/Dockerfile_debug ...
#
# The entry point CMD expects that at $GOPATH/bin/ais is the ais binary, or if that
# is absent that is should go run setup/ais.go
#

FROM ubuntu:bionic
RUN mkdir -p /usr/local/bin

RUN apt-get update && apt-get install -y wget sysstat python-pip curl nodejs collectd collectd-utils git iputils-ping netcat golang-go
RUN pip install awscli
RUN cd /opt && git clone git://github.com/etsy/statsd.git

ENV STATSD_PATH /opt/statsd
ENV STATSD_CONF statsd.conf

RUN wget http://launchpadlibrarian.net/235493456/sysstat_11.2.0-1_amd64.deb -O /tmp/sysstat_11.2.0-1_amd64.deb && dpkg -i /tmp/sysstat_11.2.0-1_amd64.deb && rm /tmp/sysstat_11.2.0-1_amd64.deb

ENV GOPATH /go
# Avoid a COPY of . which may lead to pain
COPY src /go/src
COPY bin /go/bin
COPY pkg /go/pkg

COPY src/github.com/NVIDIA/aistore/deploy/prod/kubernetes/ais_docker/ais_docker_start.sh /ais_docker_start.sh
RUN chmod a+x ais_docker_start.sh

CMD ["bash","-c", "./ais_docker_start.sh"]