package cos

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *FS) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "f":
			z.Fs, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Fs")
				return
			}
		case "t":
			z.FsType, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FsType")
				return
			}
		case "i":
			err = z.FsID.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "FsID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FS) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "f"
	err = en.Append(0x83, 0xa1, 0x66)
	if err != nil {
		return
	}
	err = en.WriteString(z.Fs)
	if err != nil {
		err = msgp.WrapError(err, "Fs")
		return
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.FsType)
	if err != nil {
		err = msgp.WrapError(err, "FsType")
		return
	}
	// write "i"
	err = en.Append(0xa1, 0x69)
	if err != nil {
		return
	}
	err = z.FsID.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "FsID")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FS) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Fs) + 2 + msgp.StringPrefixSize + len(z.FsType) + 2 + z.FsID.Msgsize()
	return
}
