package cos

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *DiskStats) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "r":
			z.RBps, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "RBps")
				return
			}
		case "s":
			z.Ravg, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Ravg")
				return
			}
		case "w":
			z.WBps, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "WBps")
				return
			}
		case "x":
			z.Wavg, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Wavg")
				return
			}
		case "u":
			z.Util, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Util")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DiskStats) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "r"
	err = en.Append(0x85, 0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.RBps)
	if err != nil {
		err = msgp.WrapError(err, "RBps")
		return
	}
	// write "s"
	err = en.Append(0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Ravg)
	if err != nil {
		err = msgp.WrapError(err, "Ravg")
		return
	}
	// write "w"
	err = en.Append(0xa1, 0x77)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.WBps)
	if err != nil {
		err = msgp.WrapError(err, "WBps")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Wavg)
	if err != nil {
		err = msgp.WrapError(err, "Wavg")
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Util)
	if err != nil {
		err = msgp.WrapError(err, "Util")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DiskStats) Msgsize() (s int) {
	s = 1 + 2 + msgp.Int64Size + 2 + msgp.Int64Size + 2 + msgp.Int64Size + 2 + msgp.Int64Size + 2 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MountpathLabel) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = MountpathLabel(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MountpathLabel) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(string(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MountpathLabel) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(string(z))
	return
}
