#
# Usage:
#  $ env IMAGE_TAG="v3.3" make all
#  $ env REGISTRY_URL="docker.io" IMAGE_REPO="aistorage/ais-util" IMAGE_TAG="v4.0" make all
#
IMAGE_REPO ?= aistorage/ais-util
BUILD_CONTEXT  = "../../../../."

include ../../docker.mk