source "https://rubygems.org"

gem "minima"
gem "wdm" if Gem.win_platform?
gem "jekyll-redirect-from"
gem "jekyll-relative-links"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"

gem "jekyll"
gem "kramdown-parser-gfm"
gem "kramdown"
gem "webrick"
