package meta

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/NVIDIA/aistore/cmn/cos"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *NetInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "h":
			z.Hostname, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hostname")
				return
			}
		case "p":
			z.Port, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "u":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "tcpEndpoint":
			z.tcpEndpoint, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "tcpEndpoint")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NetInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "h"
	err = en.Append(0x84, 0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hostname)
	if err != nil {
		err = msgp.WrapError(err, "Hostname")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteString(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	// write "tcpEndpoint"
	err = en.Append(0xab, 0x74, 0x63, 0x70, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.tcpEndpoint)
	if err != nil {
		err = msgp.WrapError(err, "tcpEndpoint")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NetInfo) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Hostname) + 2 + msgp.StringPrefixSize + len(z.Port) + 2 + msgp.StringPrefixSize + len(z.URL) + 12 + msgp.StringPrefixSize + len(z.tcpEndpoint)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Snode) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "p":
			err = z.PubNet.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "PubNet")
				return
			}
		case "d":
			err = z.DataNet.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "DataNet")
				return
			}
		case "c":
			err = z.ControlNet.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "ControlNet")
				return
			}
		case "t":
			z.DaeType, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DaeType")
				return
			}
		case "i":
			z.DaeID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DaeID")
				return
			}
		case "name":
			z.name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "name")
				return
			}
		case "e":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PubExtra")
				return
			}
			if cap(z.PubExtra) >= int(zb0002) {
				z.PubExtra = (z.PubExtra)[:zb0002]
			} else {
				z.PubExtra = make([]NetInfo, zb0002)
			}
			for za0001 := range z.PubExtra {
				err = z.PubExtra[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "PubExtra", za0001)
					return
				}
			}
		case "f":
			{
				var zb0003 uint64
				zb0003, err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "Flags")
					return
				}
				z.Flags = cos.BitFlags(zb0003)
			}
		case "g":
			z.IDDigest, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "IDDigest")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Snode) EncodeMsg(en *msgp.Writer) (err error) {
	// omitempty: check for empty values
	zb0001Len := uint32(9)
	var zb0001Mask uint16 /* 9 bits */
	if z.PubExtra == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if zb0001Len == 0 {
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = z.PubNet.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "PubNet")
		return
	}
	// write "d"
	err = en.Append(0xa1, 0x64)
	if err != nil {
		return
	}
	err = z.DataNet.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "DataNet")
		return
	}
	// write "c"
	err = en.Append(0xa1, 0x63)
	if err != nil {
		return
	}
	err = z.ControlNet.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "ControlNet")
		return
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.DaeType)
	if err != nil {
		err = msgp.WrapError(err, "DaeType")
		return
	}
	// write "i"
	err = en.Append(0xa1, 0x69)
	if err != nil {
		return
	}
	err = en.WriteString(z.DaeID)
	if err != nil {
		err = msgp.WrapError(err, "DaeID")
		return
	}
	// write "name"
	err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.name)
	if err != nil {
		err = msgp.WrapError(err, "name")
		return
	}
	if (zb0001Mask & 0x40) == 0 { // if not empty
		// write "e"
		err = en.Append(0xa1, 0x65)
		if err != nil {
			return
		}
		err = en.WriteArrayHeader(uint32(len(z.PubExtra)))
		if err != nil {
			err = msgp.WrapError(err, "PubExtra")
			return
		}
		for za0001 := range z.PubExtra {
			err = z.PubExtra[za0001].EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "PubExtra", za0001)
				return
			}
		}
	}
	// write "f"
	err = en.Append(0xa1, 0x66)
	if err != nil {
		return
	}
	err = en.WriteUint64((uint64)(z.Flags))
	if err != nil {
		err = msgp.WrapError(err, "Flags")
		return
	}
	// write "g"
	err = en.Append(0xa1, 0x67)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.IDDigest)
	if err != nil {
		err = msgp.WrapError(err, "IDDigest")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Snode) Msgsize() (s int) {
	s = 1 + 2 + z.PubNet.Msgsize() + 2 + z.DataNet.Msgsize() + 2 + z.ControlNet.Msgsize() + 2 + msgp.StringPrefixSize + len(z.DaeType) + 2 + msgp.StringPrefixSize + len(z.DaeID) + 5 + msgp.StringPrefixSize + len(z.name) + 2 + msgp.ArrayHeaderSize
	for za0001 := range z.PubExtra {
		s += z.PubExtra[za0001].Msgsize()
	}
	s += 2 + msgp.Uint64Size + 2 + msgp.Uint64Size
	return
}
