// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package meta

import (
	"github.com/NVIDIA/aistore/cmn/cos"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *NetInfo) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "h":
			z.Hostname, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Hostname")
				return
			}
		case "p":
			z.Port, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Port")
				return
			}
		case "u":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "tcpEndpoint":
			z.tcpEndpoint, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "tcpEndpoint")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NetInfo) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "h"
	err = en.Append(0x84, 0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Hostname)
	if err != nil {
		err = msgp.WrapError(err, "Hostname")
		return
	}
	// write "p"
	err = en.Append(0xa1, 0x70)
	if err != nil {
		return
	}
	err = en.WriteString(z.Port)
	if err != nil {
		err = msgp.WrapError(err, "Port")
		return
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteString(z.URL)
	if err != nil {
		err = msgp.WrapError(err, "URL")
		return
	}
	// write "tcpEndpoint"
	err = en.Append(0xab, 0x74, 0x63, 0x70, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.tcpEndpoint)
	if err != nil {
		err = msgp.WrapError(err, "tcpEndpoint")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NetInfo) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Hostname) + 2 + msgp.StringPrefixSize + len(z.Port) + 2 + msgp.StringPrefixSize + len(z.URL) + 12 + msgp.StringPrefixSize + len(z.tcpEndpoint)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PlacementConf) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "w":
			z.Weight, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Weight")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z PlacementConf) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	if z.Weight == 0 {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not omitted
		// write "w"
		err = en.Append(0xa1, 0x77)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.Weight)
		if err != nil {
			err = msgp.WrapError(err, "Weight")
			return
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z PlacementConf) Msgsize() (s int) {
	s = 1 + 2 + msgp.Int64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Snode) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "p":
			err = z.PubNet.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "PubNet")
				return
			}
		case "d":
			err = z.DataNet.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "DataNet")
				return
			}
		case "c":
			err = z.ControlNet.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "ControlNet")
				return
			}
		case "t":
			z.DaeType, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DaeType")
				return
			}
		case "i":
			z.DaeID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DaeID")
				return
			}
		case "name":
			z.name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "name")
				return
			}
		case "e":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PubExtra")
				return
			}
			if cap(z.PubExtra) >= int(zb0002) {
				z.PubExtra = (z.PubExtra)[:zb0002]
			} else {
				z.PubExtra = make([]NetInfo, zb0002)
			}
			for za0001 := range z.PubExtra {
				err = z.PubExtra[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "PubExtra", za0001)
					return
				}
			}
		case "f":
			{
				var zb0003 uint64
				zb0003, err = dc.ReadUint64()
				if err != nil {
					err = msgp.WrapError(err, "Flags")
					return
				}
				z.Flags = cos.BitFlags(zb0003)
			}
		case "g":
			z.IDDigest, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "IDDigest")
				return
			}
		case "v":
			z.VerifyingKey, err = dc.ReadBytes(z.VerifyingKey)
			if err != nil {
				err = msgp.WrapError(err, "VerifyingKey")
				return
			}
		case "pl":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Placement")
					return
				}
				z.Placement = nil
			} else {
				if z.Placement == nil {
					z.Placement = new(PlacementConf)
				}
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Placement")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Placement")
						return
					}
					switch msgp.UnsafeString(field) {
					case "w":
						z.Placement.Weight, err = dc.ReadInt64()
						if err != nil {
							err = msgp.WrapError(err, "Placement", "Weight")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Placement")
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Snode) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(11)
	var zb0001Mask uint16 /* 11 bits */
	_ = zb0001Mask
	if z.PubExtra == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.VerifyingKey == nil {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.Placement == nil {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "p"
		err = en.Append(0xa1, 0x70)
		if err != nil {
			return
		}
		err = z.PubNet.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "PubNet")
			return
		}
		// write "d"
		err = en.Append(0xa1, 0x64)
		if err != nil {
			return
		}
		err = z.DataNet.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "DataNet")
			return
		}
		// write "c"
		err = en.Append(0xa1, 0x63)
		if err != nil {
			return
		}
		err = z.ControlNet.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "ControlNet")
			return
		}
		// write "t"
		err = en.Append(0xa1, 0x74)
		if err != nil {
			return
		}
		err = en.WriteString(z.DaeType)
		if err != nil {
			err = msgp.WrapError(err, "DaeType")
			return
		}
		// write "i"
		err = en.Append(0xa1, 0x69)
		if err != nil {
			return
		}
		err = en.WriteString(z.DaeID)
		if err != nil {
			err = msgp.WrapError(err, "DaeID")
			return
		}
		// write "name"
		err = en.Append(0xa4, 0x6e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.name)
		if err != nil {
			err = msgp.WrapError(err, "name")
			return
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "e"
			err = en.Append(0xa1, 0x65)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.PubExtra)))
			if err != nil {
				err = msgp.WrapError(err, "PubExtra")
				return
			}
			for za0001 := range z.PubExtra {
				err = z.PubExtra[za0001].EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "PubExtra", za0001)
					return
				}
			}
		}
		// write "f"
		err = en.Append(0xa1, 0x66)
		if err != nil {
			return
		}
		err = en.WriteUint64((uint64)(z.Flags))
		if err != nil {
			err = msgp.WrapError(err, "Flags")
			return
		}
		// write "g"
		err = en.Append(0xa1, 0x67)
		if err != nil {
			return
		}
		err = en.WriteUint64(z.IDDigest)
		if err != nil {
			err = msgp.WrapError(err, "IDDigest")
			return
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "v"
			err = en.Append(0xa1, 0x76)
			if err != nil {
				return
			}
			err = en.WriteBytes(z.VerifyingKey)
			if err != nil {
				err = msgp.WrapError(err, "VerifyingKey")
				return
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "pl"
			err = en.Append(0xa2, 0x70, 0x6c)
			if err != nil {
				return
			}
			if z.Placement == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				// check for omitted fields
				zb0002Len := uint32(1)
				var zb0002Mask uint8 /* 1 bits */
				_ = zb0002Mask
				if z.Placement.Weight == 0 {
					zb0002Len--
					zb0002Mask |= 0x1
				}
				// variable map header, size zb0002Len
				err = en.Append(0x80 | uint8(zb0002Len))
				if err != nil {
					return
				}
				if (zb0002Mask & 0x1) == 0 { // if not omitted
					// write "w"
					err = en.Append(0xa1, 0x77)
					if err != nil {
						return
					}
					err = en.WriteInt64(z.Placement.Weight)
					if err != nil {
						err = msgp.WrapError(err, "Placement", "Weight")
						return
					}
				}
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Snode) Msgsize() (s int) {
	s = 1 + 2 + z.PubNet.Msgsize() + 2 + z.DataNet.Msgsize() + 2 + z.ControlNet.Msgsize() + 2 + msgp.StringPrefixSize + len(z.DaeType) + 2 + msgp.StringPrefixSize + len(z.DaeID) + 5 + msgp.StringPrefixSize + len(z.name) + 2 + msgp.ArrayHeaderSize
	for za0001 := range z.PubExtra {
		s += z.PubExtra[za0001].Msgsize()
	}
	s += 2 + msgp.Uint64Size + 2 + msgp.Uint64Size + 2 + msgp.BytesPrefixSize + len(z.VerifyingKey) + 3
	if z.Placement == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 2 + msgp.Int64Size
	}
	return
}
