package stats

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/NVIDIA/aistore/core"
	"github.com/NVIDIA/aistore/core/meta"
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Node) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "n":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Snode")
					return
				}
				z.Snode = nil
			} else {
				if z.Snode == nil {
					z.Snode = new(meta.Snode)
				}
				err = z.Snode.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Snode")
					return
				}
			}
		case "t":
			err = z.Tracker.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Tracker")
				return
			}
		case "x":
			err = z.Tcdf.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Tcdf")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Node) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "n"
	err = en.Append(0x83, 0xa1, 0x6e)
	if err != nil {
		return
	}
	if z.Snode == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Snode.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Snode")
			return
		}
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = z.Tracker.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Tracker")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = z.Tcdf.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Tcdf")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Node) Msgsize() (s int) {
	s = 1 + 2
	if z.Snode == nil {
		s += msgp.NilSize
	} else {
		s += z.Snode.Msgsize()
	}
	s += 2 + z.Tracker.Msgsize() + 2 + z.Tcdf.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *NodeStatus) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "r":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "RebSnap")
					return
				}
				z.RebSnap = nil
			} else {
				if z.RebSnap == nil {
					z.RebSnap = new(core.Snap)
				}
				err = z.RebSnap.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "RebSnap")
					return
				}
			}
		case "s":
			z.Status, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Status")
				return
			}
		case "d":
			z.DeploymentType, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DeploymentType")
				return
			}
		case "v":
			z.Version, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		case "b":
			z.BuildTime, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "BuildTime")
				return
			}
		case "k":
			z.K8sPodName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "K8sPodName")
				return
			}
		case "q1":
			z.Reserved1, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Reserved1")
				return
			}
		case "q2":
			z.Reserved2, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Reserved2")
				return
			}
		case "n":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Snode")
					return
				}
				z.Snode = nil
			} else {
				if z.Snode == nil {
					z.Snode = new(meta.Snode)
				}
				err = z.Snode.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Snode")
					return
				}
			}
		case "t":
			err = z.Tracker.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Tracker")
				return
			}
		case "x":
			err = z.Tcdf.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Tcdf")
				return
			}
		case "c":
			err = z.Cluster.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Cluster")
				return
			}
		case "y":
			err = z.MemCPUInfo.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "MemCPUInfo")
				return
			}
		case "w":
			z.SmapVersion, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "SmapVersion")
				return
			}
		case "q3":
			z.Reserved3, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Reserved3")
				return
			}
		case "q4":
			z.Reserved4, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Reserved4")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *NodeStatus) EncodeMsg(en *msgp.Writer) (err error) {
	// omitempty: check for empty values
	zb0001Len := uint32(16)
	var zb0001Mask uint16 /* 16 bits */
	if z.RebSnap == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Reserved1 == "" {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.Reserved2 == "" {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.Reserved3 == 0 {
		zb0001Len--
		zb0001Mask |= 0x4000
	}
	if z.Reserved4 == 0 {
		zb0001Len--
		zb0001Mask |= 0x8000
	}
	// variable map header, size zb0001Len
	err = en.WriteMapHeader(zb0001Len)
	if err != nil {
		return
	}
	if zb0001Len == 0 {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not empty
		// write "r"
		err = en.Append(0xa1, 0x72)
		if err != nil {
			return
		}
		if z.RebSnap == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.RebSnap.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "RebSnap")
				return
			}
		}
	}
	// write "s"
	err = en.Append(0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.Status)
	if err != nil {
		err = msgp.WrapError(err, "Status")
		return
	}
	// write "d"
	err = en.Append(0xa1, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.DeploymentType)
	if err != nil {
		err = msgp.WrapError(err, "DeploymentType")
		return
	}
	// write "v"
	err = en.Append(0xa1, 0x76)
	if err != nil {
		return
	}
	err = en.WriteString(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	// write "b"
	err = en.Append(0xa1, 0x62)
	if err != nil {
		return
	}
	err = en.WriteString(z.BuildTime)
	if err != nil {
		err = msgp.WrapError(err, "BuildTime")
		return
	}
	// write "k"
	err = en.Append(0xa1, 0x6b)
	if err != nil {
		return
	}
	err = en.WriteString(z.K8sPodName)
	if err != nil {
		err = msgp.WrapError(err, "K8sPodName")
		return
	}
	if (zb0001Mask & 0x40) == 0 { // if not empty
		// write "q1"
		err = en.Append(0xa2, 0x71, 0x31)
		if err != nil {
			return
		}
		err = en.WriteString(z.Reserved1)
		if err != nil {
			err = msgp.WrapError(err, "Reserved1")
			return
		}
	}
	if (zb0001Mask & 0x80) == 0 { // if not empty
		// write "q2"
		err = en.Append(0xa2, 0x71, 0x32)
		if err != nil {
			return
		}
		err = en.WriteString(z.Reserved2)
		if err != nil {
			err = msgp.WrapError(err, "Reserved2")
			return
		}
	}
	// write "n"
	err = en.Append(0xa1, 0x6e)
	if err != nil {
		return
	}
	if z.Snode == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.Snode.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Snode")
			return
		}
	}
	// write "t"
	err = en.Append(0xa1, 0x74)
	if err != nil {
		return
	}
	err = z.Tracker.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Tracker")
		return
	}
	// write "x"
	err = en.Append(0xa1, 0x78)
	if err != nil {
		return
	}
	err = z.Tcdf.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Tcdf")
		return
	}
	// write "c"
	err = en.Append(0xa1, 0x63)
	if err != nil {
		return
	}
	err = z.Cluster.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Cluster")
		return
	}
	// write "y"
	err = en.Append(0xa1, 0x79)
	if err != nil {
		return
	}
	err = z.MemCPUInfo.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "MemCPUInfo")
		return
	}
	// write "w"
	err = en.Append(0xa1, 0x77)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.SmapVersion)
	if err != nil {
		err = msgp.WrapError(err, "SmapVersion")
		return
	}
	if (zb0001Mask & 0x4000) == 0 { // if not empty
		// write "q3"
		err = en.Append(0xa2, 0x71, 0x33)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.Reserved3)
		if err != nil {
			err = msgp.WrapError(err, "Reserved3")
			return
		}
	}
	if (zb0001Mask & 0x8000) == 0 { // if not empty
		// write "q4"
		err = en.Append(0xa2, 0x71, 0x34)
		if err != nil {
			return
		}
		err = en.WriteInt64(z.Reserved4)
		if err != nil {
			err = msgp.WrapError(err, "Reserved4")
			return
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NodeStatus) Msgsize() (s int) {
	s = 3 + 2
	if z.RebSnap == nil {
		s += msgp.NilSize
	} else {
		s += z.RebSnap.Msgsize()
	}
	s += 2 + msgp.StringPrefixSize + len(z.Status) + 2 + msgp.StringPrefixSize + len(z.DeploymentType) + 2 + msgp.StringPrefixSize + len(z.Version) + 2 + msgp.StringPrefixSize + len(z.BuildTime) + 2 + msgp.StringPrefixSize + len(z.K8sPodName) + 3 + msgp.StringPrefixSize + len(z.Reserved1) + 3 + msgp.StringPrefixSize + len(z.Reserved2) + 2
	if z.Snode == nil {
		s += msgp.NilSize
	} else {
		s += z.Snode.Msgsize()
	}
	s += 2 + z.Tracker.Msgsize() + 2 + z.Tcdf.Msgsize() + 2 + z.Cluster.Msgsize() + 2 + z.MemCPUInfo.Msgsize() + 2 + msgp.Int64Size + 3 + msgp.Int64Size + 3 + msgp.Int64Size
	return
}
