# coding: utf-8

"""
    DFC

    DFC is a scalable object-storage based caching system with Amazon and Google Cloud backends.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: dfcdev@exchange.nvidia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.rebalance_target_statistics import RebalanceTargetStatistics  # noqa: E501
from openapi_client.rest import ApiException


class TestRebalanceTargetStatistics(unittest.TestCase):
    """RebalanceTargetStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRebalanceTargetStatistics(self):
        """Test RebalanceTargetStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.rebalance_target_statistics.RebalanceTargetStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
