name: Build and Push CI Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the CI image (aistorage/ci)'
        required: true
        default: 'latest'
      go_version:
        description: 'Version of GO used as the CI image base'
        required: true
        default: '1.23'

env:
  CI_IMAGE: 'aistorage/ci'

jobs:
  build-ci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push CI image
        run: |
          pushd $GITHUB_WORKSPACE/deploy/ci
          CI_IMAGE="${{ env.CI_IMAGE }}" IMAGE_TAG="${{ inputs.image_tag }}" GO_VERSION="${{ inputs.go_version }}" make -e all
          popd
