# DEPRECATION NOTICE:
# The aistorage/ci image and this workflow are deprecated.
# Please use the aistorage/gitlab-ci image and the "Docker Images" workflow instead.

name: Build and Push CI Image (DEPRECATED)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the CI image (aistorage/ci)'
        required: true
        default: 'latest'

env:
  CI_IMAGE: 'aistorage/ci'
  DOCKERFILE: 'debian.dockerfile'

jobs:
  build-ci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push CI image
        run: |
          pushd $GITHUB_WORKSPACE/deploy/ci
          IMAGE_TAG="${{ inputs.image_tag }}" make -e all
          popd
