build2:
	docker build --pull --no-cache -t aistore/python:2$$RUNTIME_TAG_MODIFIER -f Dockerfile.2 .

push2:
	docker push aistore/python:2$$RUNTIME_TAG_MODIFIER

build3:
	docker build --pull --no-cache -t aistore/python:3$$RUNTIME_TAG_MODIFIER -f Dockerfile.3 .

push3:
	docker push aistore/python:3$$RUNTIME_TAG_MODIFIER
